### ISSUE TITLE
oneOf should always use interfaces

### ISSUE THREAD

**Issue by drzony** [karlvr/openapi-generator-plus#1]
Currently, the following yaml:
```yaml
ColorRgb:
  type: object
  properties:
    r:
      type: integer
    g:
      type: integer
    b:
      type: integer
  required:
    - r
    - g
    - b
ColorHs:
  type: object
  properties:
    h:
      type: number
    s:
      type: number
  required:
    - h
    - s
SomeObject:
  type: object
  properties:
    color:
      oneOf:
        - $ref: "#/components/schemas/ColorRgb"
        - $ref: "#/components/schemas/ColorHs"
```
Produces:
```typescript
export interface ColorRgb {
  r: number;
  g: number;
  b: number;
}
export interface ColorHs {
  h: number;
  s: number;
}
export namespace SomeObject {
  export interface Color {
    r: number;
    g: number;
    b: number;
    h: number;
    s: number;
  }
}
export interface SomeObject {
  color?: Api.SomeObject.Color;
}
```
In this case since the fields are required it's impossible to create a valid object of this type.

According to OpenAPI spec `oneOf` with missing discriminator must select type based on schema:
> the payload MUST, by validation, match exactly one of the schemas

In order to avoid complicating code too much a solution would be to generate:
```typescript
export interface ColorRgb {
  r: number;
  g: number;
  b: number;
}
export interface ColorHs {
  h: number;
  s: number;
}
export interface SomeObject {
  color?: Api.ColorRgb | Api.ColorHs;
}
```
I'm eager to help, but wanted to start the discussion first

**Comment by karlvr** [comment]
@drzony hi! thank you very much for your comments. I'm pretty thrilled that you've tried out the project. 

Yes, I've made some mistakes with my treatment of inheritance vs interfaces and I've been thinking about how to resolve them; including with `allOf` and when that should use interfaces instead of inheritance. I'll try to find my notes and make some issues for these things if I can.

I think your issue represents a failure in the types module to be able to represent a type disjunction. My goal is to generate the general model of the API specification, and to model all of the necessary information in a sensible way so that the generators can use it. 

With this `oneOf` case it's like there's a `CodegenSchema` that's an array.

I'd previously thought I could get away with making the `oneOf` schema an interface, and having the concrete classes implement it, and then making use of something like the discriminator support in https://github.com/karlvr/openapi-generator-plus-generators/blob/master/packages/typescript-common/src/index.ts#L282. But as the `oneOf` can also be primitive types that doesn't quite fit. Similarly I've become aware that the model doesn't support the `any` form that I thought openapi supports but that I now can't find a link to.

I suspect there's a difference in how Java vs TypeScript would solve this;

e.g. `Api.ColorRgb | Api.ColorHs` in TypeScript might need to be `Color` where `interface Color {}` and `class ColorRgb implements Color`

Maybe the way to represent this in the model in core _is_ to generate the `Color` interface but to indicate to generators that it's just a disjunction.

I'm not convinced by my ideas yet so I welcome your input!

**Comment by drzony** [comment]
I ended up using https://www.npmjs.com/package/openapi-typescript-codegen for now, since it generates proper TypeScript in my case, however it's only generating typescript and yours can be extended to support other languages in the future (python would be nice).

Their approach is exactly as I proposed above i.e.:
`oneOf` produces:
 ```typescript
export interface SomeObject {
  color?: Api.ColorRgb | Api.ColorHs;
}
```
`allOf` produces:
```typescript
export interface AllOfInterface extends Api.ColorRgb, Api.ColorHs {
}
```
I don't quite understand why you are creating:
```typescript
export interface Color {
    r: number;
    g: number;
    b: number;
    h: number;
    s: number;
}
```
In the more complicated case `oneOf` without discriminator should have schema validation when converting from JSON, but I think it's not worth it.

**Comment by drzony** [comment]
`anyOf` is specified here https://swagger.io/specification/#schema-object
I've just checked and:
```typescript
export interface SomeObject {
 color?: Api.ColorRgb | Api.ColorHs;
}
```
Seems to be more like `anyOf` than `oneOf`

I don't think that it will be possible to represent any of them exactly, without generating some code that will validate them when request is sent, but I'm not sure whether checking the types with every request is a reasonable approach.
Other way that this could be done is a validator run in compile time (here I also think that it's not worth it)

**Comment by karlvr** [comment]
@drzony how does this look for a generated `models.ts`?

```typescript
/* eslint-disable */
// tslint:disable
/**
 * Example
 * 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

export namespace Api {
	/**
	 * 
	 * @export
	 * @interface ColorHs
	 */
	export interface ColorHs {
		/**
		 * 
		 * @type {number}
		 * @memberof ColorHs
		 */
		h: number;
		/**
		 * 
		 * @type {number}
		 * @memberof ColorHs
		 */
		s: number;
	}

	/**
	 * 
	 * @export
	 * @interface ColorRgb
	 */
	export interface ColorRgb {
		/**
		 * 
		 * @type {number}
		 * @memberof ColorRgb
		 */
		r: number;
		/**
		 * 
		 * @type {number}
		 * @memberof ColorRgb
		 */
		g: number;
		/**
		 * 
		 * @type {number}
		 * @memberof ColorRgb
		 */
		b: number;
	}

	/**
	 * 
	 * @export
	 * @interface SomeObject
	 */
	export interface SomeObject {
		/**
		 * 
		 * @type {Api.SomeObject.Color}
		 * @memberof SomeObject
		 */
		color?: Api.SomeObject.Color;
	}
	
	/**
	 * @export
	 * @namespace SomeObject
	 */
	export namespace SomeObject {
		/**
		 * 
		 * @export
		 * @interface Color
		 */
		export interface Color extends Api.ColorRgb, Api.ColorHs {
		}
	}

}
```

**Comment by karlvr** [comment]
@drzony the latest version of openapi-generator-plus and @openapi-generator-plus/typescript-fetch-generator should produce this output.

Hmm, this isn't as good as the example you provided with a disjunction... I will look at how I can do that instead.

**Comment by drzony** [comment]
@karlvr This output is great for `allOf`, but for `oneOf` this also creates the problem of all the members being required

Also, for `allOf` an alternative would be to use intersection i.e. `color?: ColorHs & ColorRgb` I think this would produce a cleaner code.

One more thing would be to use types instead of interfaces, so the final transformation would be something like:
```yaml
ColorRgb:
  type: object
  properties:
    r:
      type: integer
    g:
      type: integer
    b:
      type: integer
  required:
    - r
    - g
    - b
ColorHs:
  type: object
  properties:
    h:
      type: number
    s:
      type: number
  required:
    - h
    - s
OneOfObject:
  type: object
  properties:
    color:
      oneOf:
        - $ref: "#/components/schemas/ColorRgb"
        - $ref: "#/components/schemas/ColorHs"
AllOfObject:
  type: object
  properties:
    color:
      allOf:
        - $ref: "#/components/schemas/ColorRgb"
        - $ref: "#/components/schemas/ColorHs"
```
Would produce:
```typescript
export namespace Api {
  export type ColorHs = {
    h: number;
    s: number;
  }
  export type ColorRgb = {
    r: number;
    g: number;
    b: number;
  }
  export type OneOfObject = {
    color?: ColorHs | ColorRgb;
  }
  export type AllOfObject = {
    color?: ColorHs & ColorRgb;
  }
}
```

**Comment by karlvr** [comment]
@drzony I'm not sure about using types instead of interfaces... but I have made one fix (I had the implements things upside down) and a change to the typescript generator to recognise this situation and turn it into disjunctions (as that's a little special to TypeScript)

The generated model is now:

```typescript
export namespace Api {
	/**
	 * 
	 * @export
	 * @interface ColorHs
	 */
	export interface ColorHs {
		/**
		 * 
		 * @type {number}
		 * @memberof ColorHs
		 */
		h: number;
		/**
		 * 
		 * @type {number}
		 * @memberof ColorHs
		 */
		s: number;
	}

	/**
	 * 
	 * @export
	 * @interface ColorRgb
	 */
	export interface ColorRgb {
		/**
		 * 
		 * @type {number}
		 * @memberof ColorRgb
		 */
		r: number;
		/**
		 * 
		 * @type {number}
		 * @memberof ColorRgb
		 */
		g: number;
		/**
		 * 
		 * @type {number}
		 * @memberof ColorRgb
		 */
		b: number;
	}

	/**
	 * 
	 * @export
	 * @interface SomeObject
	 */
	export interface SomeObject {
		/**
		 * 
		 * @type {Api.ColorRgb | Api.ColorHs}
		 * @memberof SomeObject
		 */
		color?: Api.ColorRgb | Api.ColorHs;
	}
	
	/**
	 * @export
	 * @namespace SomeObject
	 */
	export namespace SomeObject {
		export type Color = Api.ColorRgb | Api.ColorHs
	}

}
```

**Comment by karlvr** [comment]
There is an interesting thing going on now, actually where I've replaced the `Color` type with the disjunction in two places... once in the definition of the `color` property and once by replacing the `interface` definition with the `type` definition with the disjunction.

This is because the former was my existing approach with oneOf with discriminators. I don't think I need to have both... I could either just remove the `type` export altogether and leave it as a disjunction everywhere, or I could keep the `type` export and use the type where the `color` property is declared. 

I think the later approach is a little truer to the intention of the API spec, and more likely to match up across different languages (such as Java, where there are no disjunctions, and so instead the `Color` must remain as an interface).

**Comment by karlvr** [comment]
I think that's improved, this is what is generated now as of https://github.com/karlvr/openapi-generator-plus-generators/commit/964135bed5cda477947bf45634a2a88a1bc72f96:

```typescript
export namespace Api {
	/**
	 * 
	 * @export
	 * @interface ColorHs
	 */
	export interface ColorHs {
		/**
		 * 
		 * @type {number}
		 * @memberof ColorHs
		 */
		h: number;
		/**
		 * 
		 * @type {number}
		 * @memberof ColorHs
		 */
		s: number;
	}

	/**
	 * 
	 * @export
	 * @interface ColorRgb
	 */
	export interface ColorRgb {
		/**
		 * 
		 * @type {number}
		 * @memberof ColorRgb
		 */
		r: number;
		/**
		 * 
		 * @type {number}
		 * @memberof ColorRgb
		 */
		g: number;
		/**
		 * 
		 * @type {number}
		 * @memberof ColorRgb
		 */
		b: number;
	}

	/**
	 * 
	 * @export
	 * @interface SomeObject
	 */
	export interface SomeObject {
		/**
		 * 
		 * @type {Api.SomeObject.Color}
		 * @memberof SomeObject
		 */
		color?: Api.SomeObject.Color;
	}
	
	/**
	 * @export
	 * @namespace SomeObject
	 */
	export namespace SomeObject {
		export type Color = Api.ColorRgb | Api.ColorHs
	}

}
```

**Comment by karlvr** [comment]
Of course the Java implementation can't handle the discriminator-less scenario the way it's now setup... as it doesn't have enough information to work out which type to deserialise as.

For the Java situation I think it might be necessary to create the monolithic class with all of the properties, all optional, and then let the user decide what to do. Possibly that monolithic class could implement all of the interfaces... it's upside down!

**Comment by drzony** [comment]
I'm not very familiar with Java, but I'll give the new version a try (probably on weekend) with my current API and give you some feedback, for now it looks great

**Comment by karlvr** [comment]
@drzony yes, I think you're right about the `allOf` scenario in TypeScript. I think it's just the situation where the `allOf` is being used to create an inheritance hierarchy that I think the extends approach is nicer. So I think it could use the `&` syntax if there is _no_ bare `type: object` in the `allOf`.

**Comment by drzony** [comment]
I don't quite understand, there is no `type:object` in the `allOf`. The type `Color` is not defined in API, so I don't see a reason why it should appear in generated code. The property is defined as a combination of 2 types, but it's not a type itself.

**Comment by karlvr** [comment]
@drzony what I mean by a bare `type: object` in the `allOf` is something like this:

```yml
Animal:
  type: object
  properties:
    name:
      type string
Cat:
  allOf:
    - $ref: '#/components/schemas/Animal'
    - type: object
      properties:
        colour:
          type: string
```

In the case of your example, the `Color` model isn't defined in the API, it is implied by the `oneOf` on the `color` property. For a language like Java, an interface is required in order to satisfy the `oneOf`, which is why the generator creates it. I've been too Java-focussed to date. For TypeScript I think it will be better _not_ to declare the nested `Color` type, and instead to type the `color` property `Api.ColorRgb | Api.ColorHs`.

If there was a named schema declared in `schema/components` that contained the `oneOf`, then I would declare it, but it would be declared as:

```typescript
type Color = Api.ColorRgb | Api.ColorHs
```

Or at least, that's what I'm working towards!

**Comment by karlvr** [comment]
I also plan to turn:

```yml
components:
  schemas:
    uuid:
      type: string
      format: uuid
```

into

```typescript
type UUID = string
```

already the Java support turns it into:

```java
java.util.UUID
```

**Comment by drzony** [comment]
Sounds great

**Comment by drzony** [comment]
I got to testing your generator with my API (sorry for the delay, I was swamped with other things). However I cannot get it to generate anything since I get the following error:
```txt
Failed to process the API specification: Error: Invalid schema type "undefined": [{"type":"string"}]
    at Object.toCodegenSchemaTypeFromSchema (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\schema-type.js:61:15)
    at toCodegenSchema (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\index.js:68:38)
    at Object.toCodegenSchemaUsage (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\index.js:47:26)
    at Object.toCodegenArraySchema (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\array.js:18:42)
    at toCodegenSchema (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\index.js:87:26)
    at Object.toCodegenSchemaUsage (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\index.js:47:26)
    at toCodegenProperty (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\object.js:357:33)
    at toCodegenProperties (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\object.js:342:26)
    at Object.toCodegenObjectSchema (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\object.js:53:24)
    at toCodegenSchema (D:\Source\projects\embedded\uc\esp\ApplicationLizards\webui\node_modules\@openapi-generator-plus\core\dist\process\schema\index.js:84:27)
```
Should I create a separate issue for that?

BTW it would be great to add the line number of the API spec which failed.

**Comment by karlvr** [comment]
@drzony OK, it's been a few months, but I think I've got the treatment of oneOf, allOf and maybe anyOf working correctly across the Java and TypeScript generators. One or two massive refactors later and I think the code is in good shape. If you're still interested, I'd love for you to check it out. If there are any issues, it would be great to get a little test spec so I can add it to my testing.

See the most recently released versions of `openapi-generator-plus` and the generators.

**Comment by drzony** [comment]
I'll be happy to take a look, but I cannot say when I'll have the time to do so.
